### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by CellyRanks** [theRSAorg/.github#1]
Readme needs an update but it might be worth conferring with comms about this.

**Comment by eirini-zormpa** [comment]
I've submitted a request for guidance from Marketing & Comms and will update once I hear back :blush:

**Comment by eirini-zormpa** [comment]
I have been in contact with Timothy from MarComms who will help with this - updated deadline 15 Feb

**Comment by eirini-zormpa** [comment]
I sent Timothy a reminder about this today

**Comment by eirini-zormpa** [comment]
The README has been updated :tada:
